package pl.cwanix.opensun.commonserver.packets.annotations;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum PacketOPCode {

    AUTH_ANS_HELLO(0x00),
    AUTH_ASK_VERIFY(0x01),
    AUTH_ANS_VERIFY(0x02),
    AUTH_ASK_AUTH(0x03),
    AUTH_ANS_AUTH(0x0E),
    AUTH_ASK_SRV_LIST(0x0F),
    AUTH_ANS_SRV_LIST(0x11),
    AUTH_ANS_SRV_STATE(0x12),
    AUTH_ASK_SRV_SELECT(0x13),
    AUTH_ANS_SRV_SELECT(0x1A),

    CONNECTION_ANS_WORLD_CONNECT(0x15),
    CONNECTION_483C(0X3C),
    CONNECTION_4860(0x60),
    CONNECTION_486C(0x6C),
    CONNECTION_ASK_ENTER_SERVER(0x76),
    CONNECTION_ANS_ENTER_VILLAGE(0x83),
    CONNECTION_ANS_ENTER_SERVER(0x98),
    CONNECTION_ASK_ENTER_VILLAGE(0x1F),
    CONNECTION_ASK_WORLD_CONNECT(0xDF),

    CHARACTER_ANS_DELETE_CHAR(0x07),
    CHARACTER_ANS_ITEMS(0x2A),
    CHARACTER_ASK_FREE_CHAR_NAME(0x51),
    CHARACTER_ASK_CREATE_CHAR(0x6F),
    CHARACTER_ERR_CREATE_CHAR(0x71),
    CHARACTER_ANS_SKILLS(0x9F),
    CHARACTER_ANS_QUICK(0xBE),
    CHARACTER_ANS_STYLE(0xC1),
    CHARACTER_ANS_STATE(0xDB),
    CHARACTER_ANS_CREATE_CHAR(0xE2),
    CHARACTER_ASK_DELETE_CHAR(0x89),

    ITEM_ERR_QUICK_LINK_SKILL(0x10),
    ITEM_ASK_QUICK_LINK_SKILL(0xC0),
    ITEM_ANS_QUICK_LINK_SKILL(0xF7),

    SKILL_ASK_ADD_SKILL_POINT(0xC5),

    STATUS_ANS_RECOVER_ATTR(0x10),
    STATUS_ANS_RECOVER_ATTR_MP(0x32),
    STATUS_ASK_STAT_SELECT(0x3C),
    STATUS_ANS_STAT_SELECT(0x7D),
    STATUS_ERR_STAT_SELECT(0x7E),

    SYNC_ANS_ALL_PLAYERS_EQUIP_INFO(0x0F),
    SYNC_ANS_PLAYER_ENTER(0x1F),
    SYNC_FD60(0x60),
    SYNC_ASK_JUMP_MOVE(0x73),
    SYNC_ASK_KEYBOARD_MOVE(0x2B),
    SYNC_ASK_MOUSE_MOVE(0xCA),
    SYNC_ASK_PLAYER_ENTER(0x8D),
    SYNC_ANS_ALL_PLAYERS_GUILD_INFO(0xEA),

    UNKNOWN_EA09(0x09),

    ZONE_ANS_VILLAGE_MOVE(0x6C),
    ZONE_ERR_VILLAGE_MOVE(0X6D),
    ZONE_ASK_VILLAGE_MOVE(0xCC);

    private final int code;

    public byte getCode() {
        return (byte) this.code;
    }
}
